[workspace]
members = [
    "angust-core", "angust_macros",                     
    "cartan",
    "complete_angust_example",
    "angust_macros",
    "test_example", 
    "test_new",
]
resolver = "2"
exclude = [
    "angust-cli"
    
]
