[package]
name = "chain_optim_backend"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0.0"
actix-rt = "2.5.0" 
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
mysql = "25.0.1" 