[package]
name = "chain_optim_frontend"
version = "0.1.0"
edition = "2021"

[dependencies]
angust = { path = "../../../crates/angust_core/" }
angust_macros = { path = "../../../crates/angust_macros/" }
tokio = "1.41.0"

[[bin]]
name = "chain_optim_frontend"
path = "src/main.rs"
