[package]
name = "cli_create_project_example"
version = "0.1.0"
edition = "2021"

[dependencies]
angust = { path = "../../crates/angust_core/" } 
angust_macros = { path = "../../crates/angust_macros/" }

tokio = "1.41.0"

[[bin]]
name = "cli_create_project_example"
path = "src/main.rs"

