[package]
name = "complete_angust_example"
version = "0.1.0"
edition = "2021"

[dependencies]
angust = { path = "../angust-core/" } 
angust_macros = { path = "../angust_macros/" }

tokio = "1.41.0"

[[bin]]
name = "complete_angust_example"
path = "src/main.rs"

